export const data = [{
        title: "Beogradski okrug",
        city: "Beograd",
        id: "RS-00",
        isCenter: ["jabucasto", "kosticavo", "jagodasto", "jezgrasto"],
    },
    {
        title: "Severnobački okrug",
        city: "Subotica",
        id: "RS-01",
        isCenter: ["jabucasto"],
    },
    {
        title: "Srednjebanatski okrug",
        city: "Zrenjanin",
        id: "RS-02",
        isCenter: ["jabucasto"],
    },
    {
        title: "Severnobanatski okrug",
        city: "Kikinda",
        id: "RS-03",
        isCenter: [],
    },
    {
        title: "Južnobanatski okrug",
        city: "Pancevo",
        id: "RS-04",
        isCenter: ["jabucasto", "kosticavo"],
    },
    {
        title: "Zapadnobački okrug",
        city: "Sombor",
        id: "RS-05",
        isCenter: ["jabucasto", "kosticavo"],
    },
    {
        title: "Južnobački okrug",
        city: "Novi Sad",
        id: "RS-06",
        isCenter: ["kosticavo"],
    },
    {
        title: "Sremski okrug",
        city: "Sremska mitrovica",
        id: "RS-07",
        isCenter: ["kosticavo"],
    },
    {
        title: "Mačvanski okrug",
        city: "Sabac",
        id: "RS-08",
        isCenter: ["kosticavo", "jagodasto"],
    },
    {
        title: "Kolubarski okrug",
        city: "Valjevo",
        id: "RS-09",
        isCenter: ["kosticavo", "jagodasto"],
    },
    {
        title: "Podunavski okrug",
        city: "Smederevo",
        id: "RS-10",
        isCenter: ["jabucasto", "kosticavo"],
    },
    {
        title: "Braničevski okrug",
        city: "Pozarevac",
        id: "RS-11",
        isCenter: ["kosticavo", "jezgrasto"],
    },
    {
        title: "Šumadijski okrug",
        city: "Kragujevac",
        id: "RS-12",
        isCenter: ["jabucasto", "kosticavo"],
    },
    {
        title: "Pomoravski okrug",
        city: "Jagodina",
        id: "RS-13",
        isCenter: ["jabucasto", "kosticavo"],
    },
    {
        title: "Borski okrug",
        city: "Bor",
        id: "RS-14",
        isCenter: ["jabucasto", "kosticavo"],
    },
    {
        title: "Zaječarski okrug",
        city: "Zajecar",
        id: "RS-15",
        isCenter: ["jabucasto", "kosticavo", "jagodasto"],
    },
    {
        title: "Zlatiborski okrug",
        city: "Uzice",
        id: "RS-16",
        isCenter: ["jabucasto", "kosticavo", "jagodasto"],
    },
    {
        title: "Moravički okrug",
        city: "Cacak",
        id: "RS-17",
        isCenter: ["jabucasto", "kosticavo", "jagodasto"],
    },
    {
        title: "Raški okrug",
        city: "Kraljevo",
        id: "RS-18",
        isCenter: ["jabucasto", "kosticavo", "jagodasto"],
    },
    {
        title: "Rasinski okrug",
        city: "Krusevac",
        id: "RS-19",
        isCenter: ["jabucasto", "kosticavo", "jagodasto", "jezgrasto"],
    },
    {
        title: "Nišavski okrug",
        city: "Nis",
        id: "RS-20",
        isCenter: ["kosticavo", "jagodasto"],
    },
    {
        title: "Toplički okrug",
        city: "Prokuplje",
        id: "RS-21",
        isCenter: ["kosticavo"],
    },
    {
        title: "Pirotski okrug",
        city: "Pirot",
        id: "RS-22",
        isCenter: ["kosticavo"],
    },
    {
        title: "Jablanički okrug",
        city: "Leskovac",
        id: "RS-23",
        isCenter: ["kosticavo", "jagodasto"],
    },
    {
        title: "Pčinjski okrug",
        city: "Vranje",
        id: "RS-24",
        isCenter: ["jabucasto", "kosticavo", "jezgrasto"],
    },
    {
        title: "Kosovski okrug",
        city: "Pristina",
        id: "RS-25",
        isCenter: [],
    },
    {
        title: "Pećki okrug",
        city: "Pec",
        id: "RS-26",
        isCenter: ["jabucasto", "kosticavo"],
    },
    {
        title: "Prizrenski okrug",
        city: "Prizren",
        id: "RS-27",
        isCenter: ["kosticavo"],
    },
    {
        title: "Kosovsko-Mitrovački okrug",
        city: "Kosovska mitrovica",
        id: "RS-28",
        isCenter: [],
    },
    {
        title: "Kosovsko-Pomoravski okrug",
        city: "Gnjilane",
        id: "RS-29",
        isCenter: [],
    },
];